### ISSUE TITLE
iOS App Center Registration Workflow

### ISSUE THREAD

**Issue by TheCodeTraveler** [brminnick/XamarinIoTWorkshop#2]
![img_0014](https://user-images.githubusercontent.com/13558917/42399786-0bd82986-8124-11e8-8320-66384fbfb5a5.PNG)
![img_0013](https://user-images.githubusercontent.com/13558917/42399787-0bf6669e-8124-11e8-9e1c-fe9dcc7c01d5.PNG)
![img_0012](https://user-images.githubusercontent.com/13558917/42399788-0c132522-8124-11e8-9ddd-5f7d9c57a9e3.PNG)
![img_0010](https://user-images.githubusercontent.com/13558917/42399790-0c33a5fe-8124-11e8-8da9-912b31aa7007.PNG)
![img_0008](https://user-images.githubusercontent.com/13558917/42399791-0c63d6c0-8124-11e8-87d7-ecf964c5b955.PNG)
![img_0007](https://user-images.githubusercontent.com/13558917/42399793-0c7ae32e-8124-11e8-87f1-3c12d29cfd5f.PNG)
![img_0006](https://user-images.githubusercontent.com/13558917/42399794-0c95e9ee-8124-11e8-88bf-aaa2634ffe77.PNG)
![img_0005](https://user-images.githubusercontent.com/13558917/42399795-0cbd3152-8124-11e8-857a-d7db238acc17.PNG)

**Comment by brminnick** [comment]
![install app](https://user-images.githubusercontent.com/13558917/45580759-3bc4cc80-b8d8-11e8-9401-4691f647715a.png)
![download app](https://user-images.githubusercontent.com/13558917/45580761-3c5d6300-b8d8-11e8-9faa-7f17d13749b3.png)
![get app](https://user-images.githubusercontent.com/13558917/45580762-3c5d6300-b8d8-11e8-9915-1458285f5251.png)
