### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by TheCodeTraveler** [brminnick/XamarinIoTWorkshop#3]
![xamariniotworkshop](https://user-images.githubusercontent.com/13558917/42401809-41173f26-812c-11e8-98f4-4703ccc062c3.gif)
<img width="1380" alt="screen shot 2018-07-06 at 2 53 06 pm" src="https://user-images.githubusercontent.com/13558917/42401851-6ceeae54-812c-11e8-9296-b3ddbf5e8249.png">

**Comment by brminnick** [comment]
![appcenterinvite](https://user-images.githubusercontent.com/13558917/42529614-d56fb1c6-8433-11e8-855a-d6e78256a7ad.png)

**Comment by brminnick** [comment]
![android app center install](https://user-images.githubusercontent.com/13558917/42529894-86e5f32a-8434-11e8-8124-555351675900.png)

**Comment by brminnick** [comment]
![android app center download download](https://user-images.githubusercontent.com/13558917/42529984-ca730290-8434-11e8-9519-92c5ced6c926.png)

**Comment by brminnick** [comment]
![android app open](https://user-images.githubusercontent.com/13558917/42530105-286af236-8435-11e8-9134-4d55785009c3.png)
![android app center install](https://user-images.githubusercontent.com/13558917/42530106-288223f2-8435-11e8-9209-b648f3991b49.png)

**Comment by brminnick** [comment]
![android open download](https://user-images.githubusercontent.com/13558917/42530233-7f0c2100-8435-11e8-9e45-507677dacb91.png)

**Comment by brminnick** [comment]
![ios app center app](https://user-images.githubusercontent.com/13558917/42534694-3d5bff02-8442-11e8-8f7f-111c0fdac6d1.png)
![img_0002](https://user-images.githubusercontent.com/13558917/42534696-3d73637c-8442-11e8-8bf4-642f0a83aa69.PNG)
![ios app center install profile install](https://user-images.githubusercontent.com/13558917/42534697-3d8a9862-8442-11e8-9524-a8c2149d1f02.png)
![ios app center install profile](https://user-images.githubusercontent.com/13558917/42534698-3da36de2-8442-11e8-89f0-c9d6964240a2.png)
![ios app center allow](https://user-images.githubusercontent.com/13558917/42534699-3dbb2fcc-8442-11e8-8216-83cde3c14812.png)
![ios app center add device](https://user-images.githubusercontent.com/13558917/42534700-3dd15450-8442-11e8-80a9-cad32e3f7d43.png)
